- name: Variables
  hosts: localhost
  vars:
    URL: play.example.com
  vars_files:
    - vars.yml
  tasks:
    - name: Print URL
      ansible.builtin.debug:
        msg: URL - {{ URL }}

    - name: Print fruit name
      ansible.builtin.debug:
        msg: FRUIT - {{ FRUIT }}
      vars:
        FRUIT: apple

    - name: Print PROJECT Name
      ansible.builtin.debug:
        msg: PROJECT_NAME - {{ PROJECT_NAME }}

    - name: Print CLI Variable
      ansible.builtin.debug:
        msg: COURSE NAME - {{COURSE_NAME}}

    - name: List Variables
      ansible.builtin.debug:
        msg: First Fruit Name - {{ FRUITS[0] }}, Second Fruit Name - {{ FRUITS[1] }}
      vars:
        FRUITS:
          - banana
          - apple
    - name: Map Variables
      ansible.builtin.debug:
        msg: Course Name - {{ COURSE["name"] }}, Trainer Name - {{ COURSE["trainer"] }}
      vars:
        COURSE:
          name: Devops
          trainer: Naveen
# You can access variable without quotes, however if the variable starting with variable then use double quotes.
# Variable not starting with value Ex: msg: URL - {{ URL }}
# Variable starting value Ex: msg: {{ URL }}

    - name: Execute shell command (Access variables Dynamically)
      ansible.builtin.shell: uptime
      register: OUT

    - name: Print OUT (Register Output)
      ansible.builtin.debug:
        msg: "{{OUT.stdout}}"
