- name: Error Handling
  hosts: localhost
  tasks:
    - name: Check User
      ansible.builtin.shell: id expense
      register: out
      ignore_errors: true

    - name: Print Output
      ansible.builtin.debug:
        msg: "{{out}}"