- name: Read Secrets
  hosts: localhost
  tasks:
    - name: Read a kv2 secret
      ansible.builtin.debug:
        msg: "{{ lookup('community.hashi_vault.vault_read', 'secret=expense-dev/data/backend {{token}} url=https://vault-internal.devopsengineer2.online:8200') }}"